RPG_LIST = {
    "NES (8-bits)": {
        "url_prefix": "https://www.spriters-resource.com/nes/",
        "games": [
            "finalfantasy",
            "finalfantasy2",
            "finalfantasy3",
            "dragonwarrior",
            "dragonwarrior2",
            "dragonwarrior3",
            "dragonwarrior4",
            "earthboundzero",
            "mother",
            "shinsekai",
            "seikendensetsu3",
            "herakles",
            "lagrange",
            "cristiano",
            "fireemblem",
            "fireemblem2",
            "willow",
            " Wizards & Warriors",
        ]
    },
    "SNES (16-bits)": {
        "url_prefix": "https://www.spriters-resource.com/snes/",
        "games": [
            "finalfantasyiv",
            "finalfantasyv",
            "finalfantasyvi",
            "chronotrigger",
            "chronocross",
            "breathoffire",
            "breathoffire2",
            "earthbound",
            "supermariorpg",
            "seikendensetsu",
            "secretsofmana",
            "gemfire",
            "robotrek",
            "shinmegamitensei",
            "shinmegamitensei2",
            "persona",
            "persona2",
            "persona2in",
            "talesofphantasia",
            "talesofsymphonia",
            "starocean",
            "starocean2",
            "suikoden",
            "suikoden2",
            "suikodentlr",
            "frontmission",
            "xenogears",
            "valkyrieprofile",
            "fft",
            "tacticsogre",
            "fireemblem",
            "fireemblemta",
            "fireemblemtr",
            "goldensun",
            "goldensun2",
            "parashunteve",
            "lunar",
            "lunar2",
            "magitechnik",
            "batenkaitos",
            "wders",
        ]
    },
    "Game Boy": {
        "url_prefix": "https://www.spriters-resource.com/gameboy/",
        "games": [
            "finalfantasylegend",
            "finalfantasylegend2",
            "finalfantasylegend3",
            "dragonwarrior1",
            "dragonwarrior2",
            "dragonwarrior3",
            "pokemonred",
            "pokemonblue",
            "pokemonyellow",
            "pokemongold",
            "pokemonsilver",
            "pokemoncrystal",
            "pikachu",
            "megamanpin",
            "zeldalink awakening",
            "metroid2",
            "wario",
            "kirby",
        ]
    },
    "GBC": {
        "url_prefix": "https://www.spriters-resource.com/gbc/",
        "games": [
            "pokemonred",
            "pokemonblue",
            "pokemonyellow",
            "pokemongold",
            "pokemonsilver",
            "pokemoncrystal",
            "pokemonpikachu",
            "dragonwarrior3",
            "dragonwarrior4",
            "finalfantasy",
            "breathoffire",
        ]
    },
    "GBA": {
        "url_prefix": "https://www.spriters-resource.com/gba/",
        "games": [
            "finalfantasy1",
            "finalfantasy2",
            "finalfantasy3",
            "finalfantasy4",
            "finalfantasy5",
            "finalfantasy6",
            "breathoffire",
            "breathoffire2",
            "breathoffire3",
            "fireemblem",
            "fireemblem2",
            "fireemblem3",
            "golden sun",
            "golden sun 2",
            "talesofphantasia",
            "talesofsymphonia",
            "starocean",
            "swordof mana",
            "mother3",
            "megamanbass",
            "megamanbn",
            "megamanbn2",
            "megamanbn3",
            "megamanbn4",
            "megamanbn5",
            "megamanbn6",
            "pokemonemerald",
            "pokemonruby",
            "pokemonsapphire",
            "pokemonfire",
            "pokemonleaf",
            "pokemonfr",
            "pokemonlg",
        ]
    },
    "PlayStation 1 (Anime)": {
        "url_prefix": "https://www.spriters-resource.com/psx/",
        "games": [
            "finalfantasyvii",
            "finalfantasyviii",
            "finalfantasyix",
            "finalfantasyx",
            "finalfantasyx2",
            "finalfantasycc",
            "finalfantasytactics",
            "xenogears",
            "xenosaga",
            "xenosaga2",
            "xenosaga3",
            "chrono cross",
            "chronotrigger",
            "parasiteeve",
            "parasiteeve2",
            "suikoden",
            "suikoden2",
            "suikoden3",
            "suikoden4",
            "suikoden5",
            "talesof destiny",
            "talesof destiny2",
            "talesof eternity",
            "talesof hearts",
            "talesof symphonia",
            "talesof the abyss",
            "talesof legends",
            "talesof rebo",
            "talesof graces",
            "talesof vesperia",
            "star ocean",
            "star ocean2",
            "star ocean3",
            "persona",
            "persona2",
            "persona3",
            "persona4",
            "shinmegamitensei",
            "shinmegamitensei2",
            "shinmegamitensei3",
            "devil survivor",
            "devil survivor2",
            "smt nocturne",
            "smt digital devil",
            "vagrant story",
            "front mission",
            "front mission3",
            "valkyrie profile",
            "valkyrie profile2",
            "wild arms",
            "wild arms2",
            "wild arms3",
            "lunar",
            "lunar2",
            "grandia",
            "grandia2",
            "ignition",
            "breath of fire",
            "breath of fire3",
            "breath of fire4",
            "dragon quest7",
            "dragon quest8",
            "drakengard",
            "baten kaitos",
            "xenosaga",
            "shadow of destiny",
            "ito",
            "uresta",
            "inmost",
            "leaf",
            "qb",
            "lost odyssey",
            "blue dragon",
            "infinite undiscovery",
            "last reminder",
            "second novel",
            "tales of Symphonia",
            "tales of the Abyss",
            "tales of Vesperia",
            "kingdom hearts",
            "kingdom hearts 2",
            "xenogears",
        ]
    },
    "PlayStation 2 (Anime)": {
        "url_prefix": "https://www.spriters-resource.com/ps2/",
        "games": [
            "finalfantasyx",
            "finalfantasyx2",
            "finalfantasyxii",
            "finalfantasyxii Revan",
            "persona3",
            "persona4",
            "persona3 FES",
            "persona4 Arena",
            "shinmegamitensei3",
            "shinmegamitensei4",
            "devil survivor",
            "smt nocturnal",
            "smt digital devil saga",
            "suikoden tactics",
            "suikoden tierkreis",
            "talesof abyss",
            "talesof vesperia",
            "talesof legendia",
            "talesof tempest",
            "talesof symphonia",
            "talesof graces",
            "talesof hearts",
            "xenosaga1",
            "xenosaga2",
            "xenosaga3",
            "xenogears",
            "wild arms4",
            "wild arms5",
            "valkyrie profile2",
            "star ocean3",
            "star ocean2",
            "lunar silver star",
            "grandia2",
            "grandia3",
            "baten kaitos origins",
            "dragon quest8",
            "drakengard2",
            "drakengard3",
            "nier",
            "automata",
            "edelweiss",
            "harvest moon",
            "clannad",
            "kanon",
            "air",
            "planetarian",
            "little busters",
            "rewrite",
            "angel beats",
            "key",
            "steins;gate",
            "chaos;head",
            "robot;ne",
            "danganronpa",
            "zero escape",
            "persona4 Arena",
            "ultimax",
            "p4d",
            "blazblue",
            "blazblue ct",
            "blazblue c2",
            "blazblue cs",
            "blazblue cf",
            "arcsys",
            "under night",
            "guilty gear",
            "nite club",
        ]
    },
    "Nintendo 64": {
        "url_prefix": "https://www.spriters-resource.com/n64/",
        "games": [
            "quest 64",
            "paper mario",
            "mario party",
            "mario party2",
            "mario party3",
            "zelda oot",
            "zelda mm",
            "majora's mask",
            "donkey kong",
            "gold",
            "yuke",
        ]
    },
    "GameCube": {
        "url_prefix": "https://www.spriters-resource.com/gamecube/",
        "games": [
            "paper mario TTYD",
            "mario party4",
            "mario party5",
            "mario party6",
            "mario party7",
            "zelda wind waker",
            "zelda four swords",
            "fire emblem",
            "fire emblem Path of Radiance",
            "fire emblem Radiant Dawn",
            "super paper mario",
            "super mario strikers",
            "mario super",
            "super mario galaxy",
        ]
    },
    "Wii": {
        "url_prefix": "https://www.spriters-resource.com/wii/",
        "games": [
            "super paper mario",
            "mario party8",
            "mario party9",
            "mario party",
            "zelda skyward sword",
            "zelda twilight princess",
            "zelda phantom hourglass",
            "fire emblem radiant dawn",
            "xenoblade chronicles",
            "last story",
            "dragon quest swords",
            "sands of destruction",
            "mario",
        ]
    },
    "Switch": {
        "url_prefix": "https://www.spriters-resource.com/switch/",
        "games": [
            "paper mario origami",
            "mario party superstars",
            "mario super star",
            "zelda botw",
            "zelda totk",
            "zelda links awakening",
            "xenoblade chronicles 2",
            "xenoblade chronicles 3",
            "fire emblem three houses",
            "fire emblem warriors",
            "fire emblem engage",
            "pokemon sword",
            "pokemon shield",
            "pokemon lets go pikachu",
            "pokemon lets go eevee",
            "pokemon brilliant diamond",
            "pokemon shining pearl",
            "pokemon legends arceus",
            "pokemon scarlet",
            "pokemon violet",
            "dragon quest XI",
            "dragon quest monsters",
            "octopath traveler",
            "octopath traveler 2",
            "triangle strategy",
            "live a live",
            "harvest moon",
            "doraemon",
            "story of seasons",
            " rune factory 4",
            "rune factory 5",
            "rune factory 3",
            "wildermyth",
            "monument valley",
            "etrian odyssey",
            "etrian untold",
            "persona5",
            "persona5 strikers",
            "persona4 Arena",
            "persona3 portable",
            "smt V",
            "smt V vengeance",
            "soul hackers 2",
            "revelations",
            "trails through",
            "trails of cold steel",
            "trails of cold steel2",
            "trails of cold steel3",
            "trails of cold steel4",
            "trails zero",
            "trails azure",
            "honkai star rail",
            "genshin impact",
            "hi3",
            "zenless zone zero",
            "blue archive",
            "arknights",
            "fgo",
            "fate grand order",
            "fate extra",
            "fate stay night",
            "priconne",
            "granblue fantasy",
            "dragalia lost",
            "dragon quest",
            "dissidia opera",
            "dissidia nt",
            "sao fatal",
            "sao hollow",
            "saoAlicization",
            "re0",
            "overlord",
            "elden ring",
            "dark souls",
            "bloodborne",
            "sekiro",
            "monster hunter",
            "legend of heroes",
        ]
    },
    "PC": {
        "url_prefix": "https://www.spriters-resource.com/pc_computer/",
        "games": [
            "final fantasy xiv",
            "final fantasy xvi",
            "genshin impact",
            "honkai star rail",
            "zenless zone zero",
            "arknights",
            "blue archive",
            "fate grand order",
            "granblue fantasy",
            "kancolle",
            "azur lane",
            "priconne",
            "dragalia lost",
            "monster hunter",
            "dauntless",
            "dragon quest x",
            "final fantasy xiv",
            "persona5",
            "smt V",
            "trails of cold steel",
            "trails through daybreak",
            "yakuza like a dragon",
            "judgment",
            "lost judgment",
            "like a dragon",
            "dragon quest heroes",
            "dissidia opera",
            "kingdom hearts",
            "nier automata",
            "nier replicant",
            "drakengard",
            "koudelka",
            "shadow of the colossus",
            "the world ends with you",
            "live a live",
            "octopath traveler",
            "triangle strategy",
            "project triangle strategy",
            "undune",
            "undune2",
            "halogen",
            "child of light",
            "wildermyth",
            "cheveron",
            "baten kaitos",
        ]
    }
}

def generate_game_urls():
    """Genera lista completa de URLs de juegos"""
    all_games = []

    for platform, data in RPG_LIST.items():
        prefix = data["url_prefix"]
        for game_slug in data["games"]:
            # Construir URL
            game_url = f"{prefix}{game_slug.replace(' ', '').lower()}/"

            # Crear nombre legible
            readable_name = game_slug.replace('-', ' ').replace('_', ' ').title()

            all_games.append({
                "platform": platform,
                "name": readable_name,
                "url": game_url,
                "slug": game_slug.lower().replace(' ', '')
            })

    return all_games

if __name__ == "__main__":
    games = generate_game_urls()
    print(f"Total de juegos en lista: {len(games)}\n")

    for i, game in enumerate(games[:50], 1):
        print(f"{i:3}. [{game['platform']:20}] {game['name']}")
        print(f"     {game['url']}")